#!/usr/bin/env ruby
require 'rubygems'
require 'active_support'

sought_md5 = ARGV.first

settings = YAML.load_file "/path/to/rails/app/database.yml"

ActiveRecord::Base.establish_connection settings["production"]

class SandboxUser < ActiveRecord::Base; end

sandbox_user = SandboxUser.find_by_identifying_hash sought_md5

if sandbox_user
  print sandbox_user.username
else
  print "Not found!"
  exit 1
end